blank_issues_enabled: false
contact_links:
  - name: Question ğŸ¤·ğŸ»â€â™‚ï¸
    url: https://github.com/trivago/prettier-plugin-sort-imports/discussions/new?category=q-a
    about: ğŸ†• Open a new Q&A discussion ğŸ™